---

- name: Remove cloud servers,CBS volumes from previous runs
  hosts: workstation_nodes
  connection: ssh
  gather_facts: False
  tasks:
    - name: Get a list of cloud servers created for the deployments in {{ rax_deploy_region }}
      shell: RAX_CREDS_FILE={{ rax_credentials_file }} RAX_REGION={{ rax_deploy_region }} python inventory/rax.py --list
      args:
        chdir: "{{ deploytempfolder }}"
      register: rax_server_list

    - set_fact:
        rax_server_list_json: "{{ rax_server_list.stdout|from_json }}"

    - debug: var=rax_server_list_json._meta.hostvars

    - name: Delete the master, slave, edge node cloud servers in {{ rax_deploy_region }}
      uri:
        url: "https://{{ rax_deploy_region }}.servers.api.rackspacecloud.com/v2/{{rax_account}}/servers/{{ item.value.rax_id }}"
        method: DELETE
        return_content: true
        status_code: 204
        headers:
          "Content-Type" : "application/json"
          "X-Auth-Token" : "{{ hostvars.localhost.rax_auth_info.json.access.token.id }}"
      when:
        - item.value.rax_metadata.group is defined
        - item.value.rax_metadata.group == "slave-nodes" or item.value.rax_metadata.group == "master-nodes" or item.value.rax_metadata.group == "edge-nodes"
      with_dict: "{{ rax_server_list_json._meta.hostvars }}"

    - name: Pause for 2 minutes for servers to really be deleted
      pause:
        minutes: 2

    - name: Get all CBS volumes list
      uri:
        url: "https://{{ rax_deploy_region }}.blockstorage.api.rackspacecloud.com/v1/{{rax_account}}/volumes"
        method: GET
        return_content: true
        status_code: 200
        headers:
          "Content-Type" : "application/json"
          "X-Auth-Token" : "{{ hostvars.localhost.rax_auth_info.json.access.token.id }}"
      register: rax_cbs_volume_list

    - name: Delete CBS volumes that we created by Jenkins runs
      uri:
        url: "https://{{ rax_deploy_region }}.blockstorage.api.rackspacecloud.com/v1/{{rax_account}}/volumes/{{ item.id }}"
        method: DELETE
        return_content: true
        status_code: 202
        headers:
          "Content-Type" : "application/json"
          "X-Auth-Token" : "{{ hostvars.localhost.rax_auth_info.json.access.token.id }}"
      when:
        - ( "slave-" in item.display_name ) or ( "master-" in item.display_name ) or ( "edge-" in item.display_name )
        - item.display_name|length == 33 or item.display_name|length == 34 or item.display_name|length == 35
      with_items: "{{ rax_cbs_volume_list.json.volumes }}"